Add new ACERetro backend service
moleculemaker/mmli-backend pull request #56
Opened 2024-07-30 18:06 UTC by KastanDay

Decide between turning ACERtro into a microservice web server OR use `docker exec` to run python scripts inside the container. Both have pros and cons.

2024-09-23 18:40 UTC, matthewberry commented on app/routers/files.py
> +        print("Getting CHEMSCRAPER job result")
this message should probably say "ACERETRO"

2024-09-23 18:41 UTC, matthewberry commented on app/routers/job.py
> +
do we still need this TODO comment?

2024-10-14 21:02 UTC, bodom0015 commented on app/cfg/local.config.yaml
> +      secretKey: "b2f9a572c7d0c822ffd2f08224529ee7"
@KastanDay we don't want to check secrets into git in a public repo, and certainly not in production .. please remove this section.

2024-10-14 21:23 UTC, bodom0015 requested changes
Please rebase to remove your last commit :pray:

2024-10-14 22:18 UTC, KastanDay commented on app/routers/files.py
> +        print("Getting CHEMSCRAPER job result")
Done, thank you!

2024-10-14 22:21 UTC, KastanDay commented on app/routers/job.py
> +
No, that has been completed. Thank you!

2024-10-18 20:34 UTC, ckouder commented on chart/values.staging.yaml
> +  aceretro_frontend_url: "https://aceretro.frontend.staging.mmli1.ncsa.illinois.edu"
update staging.yaml for frontend_url

2024-10-18 20:34 UTC, ckouder commented on chart/values.prod.yaml
> +  aceretro_frontend_url: "https://aceretro.platform.moleculemaker.org"
update prod.yaml for frontend_url

2024-10-18 20:50 UTC, bodom0015 approved these changes
LGTM :tada: Thank you for all your work on ACERetro!

2024-10-18 21:31 UTC, merged